### ISSUE TITLE
Not inheriting Rails controller behaviour?

### ISSUE THREAD

**Issue by benwalsh** [scambra/devise_invitable#760]
I have some basic custom mods to the invitations controller, like so:

```
class InvitationsController < Devise::InvitationsController
  after_action :set_email_verified!, only: :edit

  def after_accept_path_for(resource)
      user_dashboard_path(resource)
  end

  private
  
  def set_email_verified!
    session[EMAIL_VERIFIED] = resource.email_verified?
  end
end
``` 

in `routes.rb` I have configured the `devise_for` to use this controller.

Since upgrading Rails to 5.2, I get errors which imply that my controller is not inheriting standard Rails behaviour, e.g. `undefined method 'after_action' for InvitationsController:Class`, or, if I remove that callback -- or even if I remove my custom controller and the `devise_for` route mapping entirely --  `undefined method 'make_response!' for InvitationsController:Class`.

The errors are happening in the Controller, it is getting to the file and executing it as a controller, but it seems to be missing a lot of the built-in Rails functionality that makes controllers do what they do. Any thoughts?

rails 5.2.0
ruby 2.5.1
devise 4.4.3
devise_invitable 1.7.4

**Comment by benwalsh** [comment]
... and that's why catch-all/dynamic routes are considered harmful!
