### ISSUE TITLE
Generator breaks with ruby 3.2.0

### ISSUE THREAD

**Issue by tillcarlos** [scambra/devise_invitable#884]
When running the standard install process on ruby 3.2.0 it breaks here:

```ruby
undefined method `exists?' for File:Class (NoMethodError)
```

changing it to `exist?` does the trick.

**Comment by scambra** [comment]
It's fixed on master but not released or added to changelog

**Comment by scambra** [comment]
I have released 2.0.7, it should work with ruby 3.2.0
